services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

  frontend:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://api:8000
    env_file:
      - .env
